"""Added Booking Table

Revision ID: 1ce4b270fbae
Revises: 0a61ce2d3e4e
Create Date: 2025-07-21 18:10:48.034598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce4b270fbae'
down_revision = '0a61ce2d3e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('animal_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('Order_items_product_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('Order_items_order_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Orders', ['order_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ProductImages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ProductImages_product_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ProductVariants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ProductVariants_product_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductVariants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ProductVariants_product_id_fkey'), 'Products', ['product_id'], ['id'])

    with op.batch_alter_table('ProductImages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ProductImages_product_id_fkey'), 'Products', ['product_id'], ['id'])

    with op.batch_alter_table('Order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Order_items_order_id_fkey'), 'Orders', ['order_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('Order_items_product_id_fkey'), 'Products', ['product_id'], ['id'])

    op.drop_table('Bookings')
    # ### end Alembic commands ###
